export const restaurants = [
    {   
        id: 1,
        image: '/img/Restaurant/restaurant1.webp',
        location: "Futuristic land",
        name: "Pixelfood",
        maininfo: "Pixelfood offers a warm and inviting dining experience that celebrates the rich flavors of Western cuisine.",
        itemimage1: "/img/Restaurant/foodA1.webp",
        iteminfo1: "Pixel Hamburger",
        itemprice1: 40,
        itemimage2: "/img/Restaurant/foodA2.webp",
        iteminfo2: "Pixel Steak",
        itemprice2: 60,
        itemimage3: "/img/Restaurant/foodA3.webp",
        iteminfo3: "Pixel Healthy Set",
        itemprice3: 80,
    },
    {   
        id: 2,
        image: "/img/Restaurant/restaurant2.webp",
        location: "Dystopian World",
        name: "Griddiner",
        maininfo: "Welcome to The Griddiner, where culinary abundance meets warm hospitality in a vibrant, family-friendly setting.",
        itemimage1:"/img/Restaurant/foodB1.webp",
        iteminfo1: "Chinese Buffet",
        itemprice1:"300 per person",
        itemimage2:"/img/Restaurant/foodB2.webp",
        iteminfo2: "Western Buffet",
        itemprice2:"300 per person",
        itemimage3:"/img/Restaurant/foodB3.webp",
        iteminfo3: "Fusion Buffet",
        itemprice3:"300 per person",
    },
    {   
        id: 3,
        image: "/img/Restaurant/restaurant3.webp",
        location: "High-tech centre",
        name: "Synthfood",
        maininfo: "Savor expertly crafted dishes such as fresh sushi and flavorful ramen, all prepared with high-quality ingredients. ",
        itemimage1:"/img/Restaurant/foodC1.webp",
        iteminfo1: "Beef Rice",
        itemprice1: 80,
        itemimage2:"/img/Restaurant/foodC2.webp",
        iteminfo2: "Japanese Sushi set",
        itemprice2: 80,
        itemimage3:"/img/Restaurant/foodC3.webp",
        iteminfo3: "Deli Ramen",
        itemprice3: 80,
    },
    {
    id: 4,
        image: "/img/Restaurant/restaurant4.webp",
        location: "Neon Space",
        name: "Lyonrice",
        maininfo: "Lyonrice is a well-loved restaurant that specializes in serving flavorful and satisfying Filipino-style rice meals.",
        itemimage1:"/img/Restaurant/foodD1.webp",
        iteminfo1: "Sinangag",
        itemprice1: 80,
        itemimage2:"/img/Restaurant/foodD2.webp",
        iteminfo2: "Sticky Rice Cake",
        itemprice2: 80,
        itemimage3:"/img/Restaurant/foodD3.webp",
        iteminfo3: "Yellow Rice",
        itemprice3: 80,
    },
];

export const foodkiosks = [
    {   
        id: 1,
        image: "/img/FoodKiosk/kiosk1.webp",
        location: "Futuristic land",
        name: "CYER",
        maininfo: "An accessible place where users can relax while enjoying a coffee or snack in a lively, technology-focused setting.",
        itemimage1:"/img/FoodKiosk/snacksA1.webp",
        iteminfo1: "Ice Coffee",
        itemprice1: 30,
        itemimage2: "/img/FoodKiosk/snacksA2.webp",
        iteminfo2: "Healthy Sandwich",
        itemprice2: 40,
        itemimage3: "/img/FoodKiosk/snacksA3.webp",
        iteminfo3: "Coffee Cake",
        itemprice3: 25,
    },
    {   
        id: 2,
        image: "/img/FoodKiosk/kiosk2.webp",
        location: "Neon Space",
        name: "NeonFeast",
        maininfo: "It offers a vibrant experience featuring authentic Thai snacks, prepared with fresh ingredients and bold, aromatic flavors.",
        itemimage1:"/img/FoodKiosk/snacksB1.webp",
        iteminfo1: "Mee Krob",
        itemprice1: 40,
        itemimage2:"/img/FoodKiosk/snacksB2.webp",
        iteminfo2: "Moo Ping",
        itemprice2: 40,
        itemimage3:"/img/FoodKiosk/snacksB3.webp",
        iteminfo3: "Thai Fried Chicken",
        itemprice3: 40,
    },
    {   
        id: 3,
        image: "/img/FoodKiosk/kiosk3.webp",
        location: "Dystopian World",
        name: "DigitalBento",
        maininfo: "It offers a casual, accessible way to enjoy Japanese snacks with an emphasis on quality and quick service.",
        itemimage1: "/img/FoodKiosk/snacksC1.webp",
        iteminfo1: "Takoyaki",
        itemprice1: 40,
        itemimage2: "/img/FoodKiosk/snacksC2.webp",
        iteminfo2: "Okonomiyaki",
        itemprice2: 40,
        itemimage3: "/img/FoodKiosk/snacksC3.webp",
        iteminfo3: "Gyoza",
        itemprice3: 40,
    },
    {
        id: 4,
        image: "/img/FoodKiosk/kiosk4.webp",
        location: "High-tech centre",
        name: "SweetBytes",
        maininfo: "It offers a fast-paced treat experience featuring a variety of desserts, crafted with fresh ingredients and appealing flavors. ",
        itemimage1: "/img/FoodKiosk/snacksD1.webp",
        iteminfo1: "Icecream",
        itemprice1: 20,
        itemimage2: "/img/FoodKiosk/snacksD2.webp",
        iteminfo2: "Cannoli",
        itemprice2: 20,
        itemimage3: "/img/FoodKiosk/snacksD3.webp",
        iteminfo3: "Egg Waffle",
        itemprice3: 30,
    },
];

export const specialfoods = [
    {  
        id: 1,
        specialfoodsimg: "/img/SpecialFood/food1.webp", 
        title: "Kids meal",
        description: "Here you can enjoy both adorable kids plates and substantial main dishes. However, you may also send requests to the restaurants by pressing the below button preferably 24 hours in advance. "
    },
    {  
        id: 2,
        specialfoodsimg: "/img/SpecialFood/food2.webp", 
        title: "Plant-based menu items",
        description: "Plant-based meal is available in the park and at the hotels of the Cyberpunk Hong Kong. However, you may also send requests to the restaurants by pressing the below button preferably 24 hours in advance. "
    },
    {  
        id: 3,
        specialfoodsimg: "/img/SpecialFood/food3.webp", 
        title: "Halal Cuisine",
        description: "Halal-certified food is available in the park and at the hotels of the Cyberpunk Hong Kong. However, you may send you concerns to the restaurants by pressing the below button preferably 24 hours in advance."
    },
    {  
        id: 4,
        specialfoodsimg: "/img/SpecialFood/food4.webp", 
        title: "Dietary requirements",
        description: "Many Cyberpunk Hong Kong restaurants can accommodate the common food allergies. However, you may also send requests to the restaurants by pressing the below button preferably 24 hours in advance. "
    },
];

export const subscription = [
        {  
        id: 1,
        image: "/img/subscription/subscription1.webp", 
        title: "Copper",
        price: "HK$599 per year",
        advantage1:"Unlimited access for all operation weekdays",
        advantage2:"10% off car parking discount",
        advantage3:"10% off shopping discount",
        advantage4:"10% off hotel, food and Beverage discount",
        advantage5:"Birthday offers to celebrate your birthday date",

    },
    {  
        id: 2,
        image: "/img/subscription/subscription2.webp", 
        title: "Sliver",
        price: "HK$799 per year",
        advantage1:"Unlimited access for all operations days",
        advantage2:"15% off car parking discount",
        advantage3:"15% off shopping discount",
        advantage4:"15% off hotel, food and Beverage discount",
        advantage5:"Birthday offers to celebrate your birthday month"
    },
    {  
        id: 3,
        image: "/img/subscription/subscription3.webp", 
        title: "Gold",
        price: "HK$999 per year",
        advantage1:"Unlimited access for all operations days",
        advantage2:"30% off car parking discount",
        advantage3:"30% off shopping discount",
        advantage4:"30% off hotel, food and Beverage discount",
        advantage5:"Birthday offers to celebrate your birthday month"
    },
]